version: '2.4'

services:
  claim_contract_cc:
    container_name: claim_contract_cc
    image: claim-contract:1.0
    working_dir: /chaincode
    command: ["java", "-jar", "chaincode.jar"]
    environment:
      - CORE_CHAINCODE_ID_NAME=claim_contract:1.0
      - CORE_CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - "9999:9999"
    networks:
      - fabric_network
    restart: always

networks:
  fabric_network:
    external: true
